Repository TBD54566975/tbd-examples, pull requests merged in 2024-10, with the labels that each got.

#135 feat:dwa-starter-vue-app-hello-word
  javascript/dwa-starter-vue/.eslintrc.cjs
  javascript/dwa-starter-vue/.gitignore
  javascript/dwa-starter-vue/.prettierrc.json
  javascript/dwa-starter-vue/.tbd-example.json
  javascript/dwa-starter-vue/.vscode/extensions.json
  javascript/dwa-starter-vue/README.md
  javascript/dwa-starter-vue/e2e/tsconfig.json
  javascript/dwa-starter-vue/e2e/vue.spec.ts
  javascript/dwa-starter-vue/env.d.ts
  javascript/dwa-starter-vue/index.html
  javascript/dwa-starter-vue/package.json
  javascript/dwa-starter-vue/playwright.config.ts
  javascript/dwa-starter-vue/pnpm-lock.yaml
  javascript/dwa-starter-vue/postcss.config.js
  javascript/dwa-starter-vue/public/favicon.ico
  javascript/dwa-starter-vue/src/App.vue
  javascript/dwa-starter-vue/src/assets/base.css
  javascript/dwa-starter-vue/src/assets/logo.svg
  javascript/dwa-starter-vue/src/assets/main.css
  javascript/dwa-starter-vue/src/main.ts
  javascript/dwa-starter-vue/src/stores/counter.ts
  javascript/dwa-starter-vue/tailwind.config.js
  javascript/dwa-starter-vue/tests/App.spec.ts
  javascript/dwa-starter-vue/tsconfig.app.json
  javascript/dwa-starter-vue/tsconfig.json
  javascript/dwa-starter-vue/tsconfig.node.json
  javascript/dwa-starter-vue/tsconfig.vitest.json
  javascript/dwa-starter-vue/vite.config.ts
  javascript/dwa-starter-vue/vitest.config.ts
Labels: hacktoberfest, medium

#194 Create About page component (#69)
  javascript/dwa-starter-vue/src/views/AboutView.vue
Labels: hacktoberfest, small, hacktoberfest-accepted

#176 Feat/dark mode
  javascript/dwa-starter-vue/package.json
  javascript/dwa-starter-vue/pnpm-lock.yaml
  javascript/dwa-starter-vue/src/App.vue
  javascript/dwa-starter-vue/src/components/NavList.vue
  javascript/dwa-starter-vue/src/components/NavMenu.vue
  javascript/dwa-starter-vue/src/components/ui/dropdown-menu/DropdownMenu.vue
  javascript/dwa-starter-vue/src/components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue
  javascript/dwa-starter-vue/src/components/ui/dropdown-menu/DropdownMenuContent.vue
  javascript/dwa-starter-vue/src/components/ui/dropdown-menu/DropdownMenuGroup.vue
  javascript/dwa-starter-vue/src/components/ui/dropdown-menu/DropdownMenuItem.vue
  javascript/dwa-starter-vue/src/components/ui/dropdown-menu/DropdownMenuLabel.vue
  javascript/dwa-starter-vue/src/components/ui/dropdown-menu/DropdownMenuRadioGroup.vue
  javascript/dwa-starter-vue/src/components/ui/dropdown-menu/DropdownMenuRadioItem.vue
  javascript/dwa-starter-vue/src/components/ui/dropdown-menu/DropdownMenuSeparator.vue
  javascript/dwa-starter-vue/src/components/ui/dropdown-menu/DropdownMenuShortcut.vue
  javascript/dwa-starter-vue/src/components/ui/dropdown-menu/DropdownMenuSub.vue
  javascript/dwa-starter-vue/src/components/ui/dropdown-menu/DropdownMenuSubContent.vue
  javascript/dwa-starter-vue/src/components/ui/dropdown-menu/DropdownMenuSubTrigger.vue
  javascript/dwa-starter-vue/src/components/ui/dropdown-menu/DropdownMenuTrigger.vue
  javascript/dwa-starter-vue/src/components/ui/dropdown-menu/index.ts
  javascript/dwa-starter-vue/src/components/ui/navigation-menu/NavigationMenu.vue
  javascript/dwa-starter-vue/src/components/ui/navigation-menu/NavigationMenuContent.vue
  javascript/dwa-starter-vue/src/components/ui/navigation-menu/NavigationMenuIndicator.vue
  javascript/dwa-starter-vue/src/components/ui/navigation-menu/NavigationMenuItem.vue
  javascript/dwa-starter-vue/src/components/ui/navigation-menu/NavigationMenuLink.vue
  javascript/dwa-starter-vue/src/components/ui/navigation-menu/NavigationMenuList.vue
  javascript/dwa-starter-vue/src/components/ui/navigation-menu/NavigationMenuTrigger.vue
  javascript/dwa-starter-vue/src/components/ui/navigation-menu/NavigationMenuViewport.vue
  javascript/dwa-starter-vue/src/components/ui/navigation-menu/index.ts
  javascript/dwa-starter-vue/tests/App.spec.ts
Labels: hacktoberfest, medium, hacktoberfest-accepted

#195 Feat/pwa
  javascript/dwa-starter-vue/e2e/vue.spec.ts
  javascript/dwa-starter-vue/index.html
  javascript/dwa-starter-vue/package.json
  javascript/dwa-starter-vue/pnpm-lock.yaml
  javascript/dwa-starter-vue/public/apple-touch-icon-180x180.png
  javascript/dwa-starter-vue/public/favicon.ico
  javascript/dwa-starter-vue/public/favicon.svg
  javascript/dwa-starter-vue/public/maskable-icon-512x512.png
  javascript/dwa-starter-vue/public/pwa-192x192.png
  javascript/dwa-starter-vue/public/pwa-512x512.png
  javascript/dwa-starter-vue/public/pwa-64x64.png
  javascript/dwa-starter-vue/public/robots.txt
  javascript/dwa-starter-vue/public/screenshot-desktop.png
  javascript/dwa-starter-vue/public/screenshot-mobile.png
  javascript/dwa-starter-vue/public/workplace.svg
  javascript/dwa-starter-vue/src/App.vue
  javascript/dwa-starter-vue/src/components/NavList.vue
  javascript/dwa-starter-vue/src/components/NavMenu.vue
  javascript/dwa-starter-vue/src/components/ui/form/FormControl.vue
  javascript/dwa-starter-vue/src/components/ui/form/FormDescription.vue
  javascript/dwa-starter-vue/src/components/ui/form/FormItem.vue
  javascript/dwa-starter-vue/src/components/ui/form/FormLabel.vue
  javascript/dwa-starter-vue/src/components/ui/form/FormMessage.vue
  javascript/dwa-starter-vue/src/components/ui/form/index.ts
  javascript/dwa-starter-vue/src/components/ui/form/injectionKeys.ts
  javascript/dwa-starter-vue/src/components/ui/form/useFormField.ts
  javascript/dwa-starter-vue/src/components/ui/input/Input.vue
  javascript/dwa-starter-vue/src/components/ui/input/index.ts
  javascript/dwa-starter-vue/src/components/ui/label/Label.vue
  javascript/dwa-starter-vue/src/components/ui/label/index.ts
  javascript/dwa-starter-vue/src/components/ui/toast/Toast.vue
  javascript/dwa-starter-vue/src/components/ui/toast/ToastAction.vue
  javascript/dwa-starter-vue/src/components/ui/toast/ToastClose.vue
  javascript/dwa-starter-vue/src/components/ui/toast/ToastDescription.vue
  javascript/dwa-starter-vue/src/components/ui/toast/ToastProvider.vue
  javascript/dwa-starter-vue/src/components/ui/toast/ToastTitle.vue
  javascript/dwa-starter-vue/src/components/ui/toast/ToastViewport.vue
  javascript/dwa-starter-vue/src/components/ui/toast/Toaster.vue
  javascript/dwa-starter-vue/src/components/ui/toast/index.ts
  javascript/dwa-starter-vue/src/components/ui/toast/use-toast.ts
  javascript/dwa-starter-vue/src/main.ts
  javascript/dwa-starter-vue/src/pwa.ts
  javascript/dwa-starter-vue/src/types.d.ts
  javascript/dwa-starter-vue/src/views/AboutView.vue
  javascript/dwa-starter-vue/src/views/HomeView.vue
  javascript/dwa-starter-vue/src/views/SettingsView.vue
  javascript/dwa-starter-vue/tests/App.spec.ts
  javascript/dwa-starter-vue/vite.config.ts
Labels: hacktoberfest, large, hacktoberfest-accepted

#148 DWA Starter: Create basic "Hello World" Vanilla.js app
  javascript/dwa-starter-vanillajs-vite/.gitignore
  javascript/dwa-starter-vanillajs-vite/.tbd-example.json
  javascript/dwa-starter-vanillajs-vite/index.html
  javascript/dwa-starter-vanillajs-vite/main.js
  javascript/dwa-starter-vanillajs-vite/package.json
  javascript/dwa-starter-vanillajs-vite/playwright.config.js
  javascript/dwa-starter-vanillajs-vite/pnpm-lock.yaml
  javascript/dwa-starter-vanillajs-vite/public/vite.svg
  javascript/dwa-starter-vanillajs-vite/style.css
  javascript/dwa-starter-vanillajs-vite/tests/main.spec.js
  javascript/dwa-starter-vanillajs-vite/vite.config.js
Labels: hacktoberfest, medium, hacktoberfest-accepted

#201 Create README with instructions on running and installing project - Vue
  javascript/dwa-starter-vue/README.md
Labels: hacktoberfest

#208 Create README with instructions on running and installing project - Vanilla.js
  javascript/dwa-starter-vanillajs-vite/readme.md
Labels: hacktoberfest, medium, hacktoberfest-accepted

#221 Create routes for pages in Vanilla.js app
  javascript/dwa-starter-vanillajs-vite/components.js
  javascript/dwa-starter-vanillajs-vite/index.html
  javascript/dwa-starter-vanillajs-vite/main.js
  javascript/dwa-starter-vanillajs-vite/package.json
  javascript/dwa-starter-vanillajs-vite/pnpm-lock.yaml
  javascript/dwa-starter-vanillajs-vite/style.css
  javascript/dwa-starter-vanillajs-vite/tests/main.spec.js
Labels: hacktoberfest, medium, hacktoberfest-accepted

#196 Feat/dwa
  javascript/dwa-starter-vue/e2e/vue.spec.ts
  javascript/dwa-starter-vue/globals.d.ts
  javascript/dwa-starter-vue/package.json
  javascript/dwa-starter-vue/pnpm-lock.yaml
  javascript/dwa-starter-vue/src/App.vue
  javascript/dwa-starter-vue/src/components/NavList.vue
  javascript/dwa-starter-vue/src/components/Sidebar.vue
  javascript/dwa-starter-vue/src/components/SidebarList.vue
  javascript/dwa-starter-vue/src/components/TodoList.vue
  javascript/dwa-starter-vue/src/components/Web5ConnectButton.vue
  javascript/dwa-starter-vue/src/components/ui/drawer/Drawer.vue
  javascript/dwa-starter-vue/src/components/ui/drawer/DrawerContent.vue
  javascript/dwa-starter-vue/src/components/ui/drawer/DrawerDescription.vue
  javascript/dwa-starter-vue/src/components/ui/drawer/DrawerFooter.vue
  javascript/dwa-starter-vue/src/components/ui/drawer/DrawerHeader.vue
  javascript/dwa-starter-vue/src/components/ui/drawer/DrawerOverlay.vue
  javascript/dwa-starter-vue/src/components/ui/drawer/DrawerTitle.vue
  javascript/dwa-starter-vue/src/components/ui/drawer/index.ts
  javascript/dwa-starter-vue/src/composables/web5.ts
  javascript/dwa-starter-vue/src/composables/web5Connection.ts
  javascript/dwa-starter-vue/src/lib/protocols.ts
  javascript/dwa-starter-vue/src/lib/todo-dwn-repository.ts
  javascript/dwa-starter-vue/src/main.ts
  javascript/dwa-starter-vue/src/router/index.ts
  javascript/dwa-starter-vue/src/stores/counter.ts
  javascript/dwa-starter-vue/src/stores/web5.ts
  javascript/dwa-starter-vue/src/sw.ts
  javascript/dwa-starter-vue/src/views/AboutView.vue
  javascript/dwa-starter-vue/src/views/HomeView.vue
  javascript/dwa-starter-vue/src/views/SettingsView.vue
  javascript/dwa-starter-vue/tests/App.spec.ts
  javascript/dwa-starter-vue/tsconfig.app.json
  javascript/dwa-starter-vue/vite.config.ts
Labels: hacktoberfest, large

#233 Create about page component - Vanilla.js
  javascript/dwa-starter-vanillajs-vite/components.js
  javascript/dwa-starter-vanillajs-vite/index.html
  javascript/dwa-starter-vanillajs-vite/package.json
  javascript/dwa-starter-vanillajs-vite/pnpm-lock.yaml
  javascript/dwa-starter-vanillajs-vite/style.css
  javascript/dwa-starter-vanillajs-vite/tailwind.config.js
  javascript/dwa-starter-vanillajs-vite/tests/main.spec.js
Labels: hacktoberfest

#199 Feat/todo
  javascript/dwa-starter-vue/src/components/TodoList.vue
  javascript/dwa-starter-vue/src/components/ui/checkbox/Checkbox.vue
  javascript/dwa-starter-vue/src/components/ui/checkbox/index.ts
  javascript/dwa-starter-vue/src/components/ui/table/Table.vue
  javascript/dwa-starter-vue/src/components/ui/table/TableBody.vue
  javascript/dwa-starter-vue/src/components/ui/table/TableCaption.vue
  javascript/dwa-starter-vue/src/components/ui/table/TableCell.vue
  javascript/dwa-starter-vue/src/components/ui/table/TableEmpty.vue
  javascript/dwa-starter-vue/src/components/ui/table/TableFooter.vue
  javascript/dwa-starter-vue/src/components/ui/table/TableHead.vue
  javascript/dwa-starter-vue/src/components/ui/table/TableHeader.vue
  javascript/dwa-starter-vue/src/components/ui/table/TableRow.vue
  javascript/dwa-starter-vue/src/components/ui/table/index.ts
  javascript/dwa-starter-vue/src/composables/web5.ts
  javascript/dwa-starter-vue/src/main.ts
  javascript/dwa-starter-vue/src/views/SettingsView.vue
Labels: hacktoberfest, large, hacktoberfest-accepted

#320 Add dark mode/light theme - Vanilla.js #84
  javascript/dwa-starter-vanillajs-vite/components.js
  javascript/dwa-starter-vanillajs-vite/index.html
  javascript/dwa-starter-vanillajs-vite/main.js
  javascript/dwa-starter-vanillajs-vite/package-lock.json
  javascript/dwa-starter-vanillajs-vite/style.css
  javascript/dwa-starter-vanillajs-vite/tailwind.config.js
  javascript/dwa-starter-vanillajs-vite/tests/main.spec.js
Labels: hacktoberfest, large, hacktoberfest-accepted

#263 Feat/settings
  javascript/dwa-starter-vue/package.json
  javascript/dwa-starter-vue/pnpm-lock.yaml
  javascript/dwa-starter-vue/src/components/TodoList.vue
  javascript/dwa-starter-vue/src/composables/web5.ts
  javascript/dwa-starter-vue/src/lib/drls.ts
  javascript/dwa-starter-vue/src/sw.ts
  javascript/dwa-starter-vue/src/views/SettingsView.vue
  javascript/dwa-starter-vue/vite.config.ts
Labels: hacktoberfest, large, hacktoberfest-accepted

#356 Feat/wallet connect
  javascript/dwa-starter-vue/.gitignore
  javascript/dwa-starter-vue/package.json
  javascript/dwa-starter-vue/pnpm-lock.yaml
  javascript/dwa-starter-vue/src/components/TodoList.vue
  javascript/dwa-starter-vue/src/components/Web5ConnectButton.vue
  javascript/dwa-starter-vue/src/composables/web5.ts
  javascript/dwa-starter-vue/src/composables/web5Connection.ts
  javascript/dwa-starter-vue/src/stores/web5.ts
  javascript/dwa-starter-vue/src/views/SettingsView.vue
Labels: hacktoberfest, hacktoberfest-accepted
